version: '3.13'

services:
  markdown-app:
    container_name: markdown-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      FLASK_ENV: development